//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFN_PMQL_Shop_Giay_Dep_Nam05012023_CDBK_LTMT1_CĐ1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sản_Phẩm
    {
        public int Mã_Sản_Phẩm { get; set; }
        public string Tên_Sản_Phẩm { get; set; }
        public Nullable<int> Năm_Sản_Xuất { get; set; }
        public Nullable<double> Đơn_Giá { get; set; }
        public string Mã_Màu { get; set; }
        public Nullable<bool> BIT_Kho_Hàng { get; set; }
        public string Kho_Hàng { get; set; }
        public string Ảnh { get; set; }
        public Nullable<int> Size { get; set; }
    }
}
